#!/bin/bash

# This file was automatically generated by
# METATOOLS_SELF
# at METATOOLS_TIME.

# Remove OS X's automatic Process Serial Number. There is apparently no way for
# us to detect if this will be passed beyond simply looking for it, so make sure
# that you don't `open` one of these apps and pass it a single argument that
# starts with "-psn", or it will be removed.
if [[ "$#" == 1 && "${1:0:4}" == "-psn" ]]; then
    shift
fi

# Build the environment if it doesn't already exist. We try to recreate the
# bash environment as if invocated with "--login".
if [[ "$SHLVL" < 2 ]]; then
    
    # Global profile.
    if [[ -f /etc/profile ]]; then
        source /etc/profile
    fi
    
    # User profile.
    for x in ~/.bash_profile ~/.bash_login ~/.profile; do
        if [[ -f $x ]]; then
            source $x
            break
        fi
    done

fi

# Move onto the next step.
exec "$(dirname "$0")/METATOOLS_NEXT" "$@"
