#!/usr/bin/env python

# This file was automatically generated by
# METATOOLS_SELF
# at METATOOLS_TIME.

import os
import sys


def _bootstrap():

    command = METATOOLS_COMMAND
    execfile_ = METATOOLS_EXECFILE
    entrypoint = METATOOLS_ENTRYPOINT

    if command:
        # We loaded python just to do this?
        os.execvp(command, [command] + sys.argv[1:])
        exit(1) # Never reached.

    if execfile_:
        globals_ = {'__name__': '__main__'}
        execfile(execfile_, globals_, globals_)
        exit(0)

    if entrypoint:
        entrypoint = entrypoint.split(':')
        module = __import__(entrypoint[0], fromlist=['.'])
        if len(entrypoint) > 1:
            attrs = entrypoint[1].split('.')
            head = module
            for attr in attrs:
                head = getattr(head, attr, None)
                if head is None:
                    print >> sys.stderr, entrypoint, 'does not exist'
                    exit(2)
            head()
        exit(0)

    print >> sys.stderr, 'metatools.app: unknown bootstrapping type'
    exit(3)



_bootstrap()
